name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for backend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test

      - name: Build Docker image for backend
        working-directory: ./backend
        run: docker build -t roman-service .

      # Run built Docker container + health check
      - name: Run Docker container and check health endpoint
        run: |
          docker run -d -p 8080:8080 roman-service
          sleep 5
          curl -f http://localhost:8080/health

  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./frontend
        # Disable watch mode for CI
        run: npm test -- --watchAll=false

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build